"""
OpenRouter Account Setup Guide
"""

print("🚀 Getting Your OpenRouter API Key")
print("=" * 50)
print()
print("Step 1: Visit OpenRouter")
print("- Go to: https://openrouter.ai/")
print("- This is a service that provides access to multiple AI models")
print()
print("Step 2: Create Account")
print("- Click 'Sign Up' or 'Get Started'")
print("- Create your account")
print()
print("Step 3: Get API Key")
print("- After logging in, go to your dashboard")
print("- Look for 'API Keys' or 'Settings'")
print("- Generate a new API key")
print("- It should look like: sk-or-v1-[long string]")
print()
print("Step 4: Check Credits")
print("- OpenRouter provides some free credits")
print("- You can add more credits if needed")
print("- Free tier includes access to several models")
print()
print("Step 5: Update .env file")
print("- Replace 'poetrypartner' with your actual API key")
print("- Should look like: OPENROUTER_API_KEY=sk-or-v1-your_actual_key_here")
print()
print("🆓 Free Models Available:")
print("- meta-llama/llama-3.1-8b-instruct:free")
print("- microsoft/phi-3-mini-128k-instruct:free") 
print("- google/gemma-2-9b-it:free")
print()
print("💡 Alternative: If you prefer, you can also use:")
print("- OpenAI API (from openai.com)")
print("- Anthropic Claude API")
print("- Google Gemini API")
print("- But OpenRouter gives you access to many models with one key!")